# Generated by Django 3.2 on 2021-05-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='UserInfo',
            new_name='userInfo',
        ),
    ]
